(in-package :grader)

;; Weights used for calculating final grade

(defconstant +style-bonus-mark+ 10)

(defconstant +similarity-threshold+ 0.5)

(defconstant +correctness-weight+ 0.7)

(defconstant +style-weight+ 0.3)


(defun check-assessment-violations (target-func program forbidden-list)
  "Analyzes the program for forbidden function calls, even if nested 
   in helper functions. Returns a list of (FUNCTION . VIOLATIONS).
   Returns nil if program is nil"
  (let* ((graph (get-call-graph target-func program))
         (report '()))
    (dolist (node graph)
      (let* ((func-name (car node))
             (calls (second node))
             (violations (intersection calls forbidden-list)))
        (when violations
          (push (cons func-name violations) report))))
    report))

(defun summarize-results (q-label results)
  "Aggregates FiveAM result objects into a summarized report."
  (let ((total (length results))
        (passed (count-if (lambda (res) 
                            (typep res 'fiveam::test-passed)) 
                          results))
        (failures (remove-if (lambda (res) 
                               (typep res 'fiveam::test-passed)) 
                             results)))
    (list :q-label q-label
          :score (if (zerop total) 0 (float (* 100   (/ passed total))))
          :stats (list :total total :passed passed :failed (length failures))
          ;; Map the failures into a clean feedback list
          :feedback (mapcar (lambda (f)
                              (list :expr (fiveam::test-expr f)
                                    :reason (fiveam::reason f)
                                    :type (type-of f)))
                            failures))))

(defun critique-student-solution (sol)
  (let ((output (with-output-to-string (*standard-output*)
                  (lisp-critic:critique-file sol))))
    ;; We check if the output contains a hint (usually starts with a paren or keyword)
    ;; Adjust the search string based on what lisp-critic actually outputs
    (format t "~%--- Style Feedback ---~%~%Below is your 'pretty-printed' code. ")
    (if (search "----" output :test #'char-equal)
        (format t "The suggestions below your code can ~%help you write more 'Lisp-y' solutions:~%~%~A" output)
        (format t "No idiomatic improvements suggested.~%~%~A" output))))

(defun grade-student (student-file q-label fname kind)
  "Loads the student's program file in the sandbox,
   depending on KIND runs the given or hidden fiveam test cases, 
   and collects the results"
  (let ((runner-name (intern (format nil "RUN-~A-~A-~A-TEST" q-label fname kind) :sandbox)))
    ;; 1. Load student code
    
    (handler-case (with-package :sandbox
                    (load student-file))
      (error (c) (return-from grade-student
                   (list :q-label q-label :score 0.0 :error (format nil "Load Error: ~A" c)))))
    
    ;; 2. Execute the pre-compiled runner
    (let* ((raw-results (funcall runner-name))
           (summary (summarize-results q-label raw-results)))
      summary)))

(defun calc-final-mark (correctness similarity professor-solution)
  "Calculates the final grade and generates a feedback report.
   
   Arguments:
   - correctness: Functional score (0-100).
   - similarity: Style similarity metric (0.0-1.0).
   - professor-solution: The normalized instructor code used for comparison.

   Returns:
   1. The feedback string generated by generate-similarity-report.
   2. The final calculated score (float)."
  (let ((rounded-sim (/ (round (* similarity 10)) 10.0)))
    (multiple-value-bind (final-score case-type)
        (calculate-weighted-score correctness rounded-sim)
      (let ((feedback (generate-similarity-report case-type 
                                                 correctness 
                                                 rounded-sim 
                                                 professor-solution)))
        (values feedback final-score)))))


;; --- Logic Layer ---

(defun calculate-weighted-score (correctness similarity)
  "Pure logic for determining the score. Returns (values score case-symbol)."
  (let* ((weighted (+ (* correctness +correctness-weight+) 
                      (* similarity 100 +style-weight+)))
         (base     (max correctness weighted)))
    (cond 
      ((and (= correctness 100) (>= similarity +similarity-threshold+))
       (values (+ base (* +style-bonus-mark+ similarity)) :bonus))
      ((= correctness 100)
       (values 100.0 :perfect-no-bonus))
      (t 
       (values base :standard)))))

;; --- Presentation Layer ---

(defun generate-similarity-report (case-type correctness similarity prof-sol)
  "Handles all string formatting based on the specific grading scenario."
  (case case-type
    (:bonus
     (format nil "Calculation: (+ CORRECTNESS (* MAX-STYLE-BONUS STYLE-SIMILARITY))~%~
                  - Correctness: ~,2F~%~
                  - Similarity: ~a (>= threshold ~a)~%~
                  - Reference Code:~%~s"
             correctness similarity +similarity-threshold+ prof-sol))
    (:perfect-no-bonus
     (format nil "Calculation: (+ CORRECTNESS 0.0)~%~
                  - Correctness: ~,2F~%~
                  - Note: Similarity ~a is below ~a for bonus.~%~
                  - Reference Code:~%~s"
             correctness similarity +similarity-threshold+ prof-sol))
    (:standard
     (let ((drift-msg (if (zerop similarity) 
                          "Note: Your logic varies significantly." 
                          "Note: High structural similarity found.")))
       (format nil "Calculation: (MAX CORRECTNESS (+ (* C Wc) (* S Ws)))~%~
                    - Correctness: ~,2F (~a weight)~%~
                    - Style Weight: ~a~%~
                    - Similarity: ~a~%~
                    - ~A~%~
                    - Reference Code:~%~s"
               correctness +correctness-weight+ +style-weight+ 
               similarity drift-msg prof-sol)))))
