(in-package :grader)

;; Weights used for calculating final grade

(defconstant +style-bonus-mark+ 10)

(defconstant +similarity-threshold+ 0.5)

(defconstant +correctness-weight+ 0.7)

(defconstant +style-weight+ 0.3)


(defun check-assessment-violations (target-func program forbidden-list)
  "Analyzes the program for forbidden function calls, even if nested 
   in helper functions. Returns a list of (FUNCTION . VIOLATIONS).
   Returns nil if program is nil"
  (let* ((graph (get-call-graph target-func program))
         (report '()))
    (dolist (node graph)
      (let* ((func-name (car node))
             (calls (second node))
             (violations (intersection calls forbidden-list)))
        (when violations
          (push (cons func-name violations) report))))
    report))

(defun critique-student-solution-style (sol)
  (let ((output (with-output-to-string (*standard-output*)
                  (lisp-critic:critique-file sol))))
    ;; We check if the output contains a hint (usually starts with a paren or keyword)
    ;; Adjust the search string based on what lisp-critic actually outputs
    (format t "~%--- Style Feedback ---~%~%Below is your 'pretty-printed' code. ")
    (if (search "----" output :test #'char-equal)
        (format t "The suggestions below your code can ~%help you write more 'Lisp-y' solutions:~%~%~A" output)
        (format t "No idiomatic improvements suggested.~%~%~A" output))))

(defun grade-student (student-file q-label fname kind)
  "Loads the student's program file in the tester sandbox,
   depending on KIND runs the given or hidden fiveam test cases, 
   and collects the results"
  (let ((runner-name (intern (format nil "~A-~A-~A-TEST" q-label fname kind) *tester-package*)))    
    ;; Execute the pre-compiled runner
    (format t "Grading ~a - ~a -  " q-label student-file)
    (let* ((raw-results (funcall runner-name student-file))
           (summary (summarize-results q-label raw-results)))
      summary)))

(defun calc-final-mark (score-history similarity professor-solution)
  "Calculates the final grade and generates a feedback report.
   
   Arguments:
   - score-history: A plist (:functional-score value :violation-score value).
   - similarity: Style similarity metric (0.0-1.0).
   - professor-solution: The normalized instructor code used for comparison.

   Returns:
   1. The feedback string generated by generate-similarity-report.
   2. The final calculated score (float)."
  (let ((rounded-sim (/ (round (* similarity 10)) 10.0)))
    (multiple-value-bind (final-score case-type)
        (calculate-weighted-score (getf score-history :violation-score) rounded-sim)
      (let ((feedback (generate-similarity-report case-type 
                                                  (append (list :similarity-bonus-score final-score) score-history) 
                                                  rounded-sim 
                                                  professor-solution)))
        (values feedback final-score)))))


;; --- Logic Layer ---

(defun calculate-weighted-score (correctness similarity)
  "Pure logic for determining the score. Returns (values score case-symbol)."
  (let* ((weighted (+ (* correctness +correctness-weight+) 
                      (* similarity 100 +style-weight+)))
         (base     (max correctness weighted)))
    (cond 
      ((and (= correctness 100) (>= similarity +similarity-threshold+))
       (values (+ base (* +style-bonus-mark+ similarity)) :bonus))
      ((= correctness 100)
       (values 100.0 :perfect-no-bonus))
      (t 
       (values base :standard)))))

;; --- Presentation Layer ---

(defun generate-similarity-report (case-type score-history similarity prof-sol)
  "Handles all string formatting based on the specific grading scenario."
  (case case-type
    (:bonus
     (format nil "Final Score: ~,2F, [0 to ~A]~%Calculation: (+ CORRECTNESS (* MAX-STYLE-BONUS SIMILARITY))~%~
                  - Correctness: ~,2F, [0 to 100]~%~
                  - Max Style Bonus: ~,2F~%~
                  - Similarity: ~,2F, [0 to 1] >= threshold of ~a~%~
                  - Reference Solution:~%~s"
             (getf score-history :similarity-bonus-score)
             (+ 100 +style-bonus-mark+)
             (getf score-history :violation-score)
             +style-bonus-mark+
             similarity
             +similarity-threshold+ prof-sol))
    (:perfect-no-bonus
     (format nil "Final Score: ~,2F, [0 to 100]~%Calculation: (+ CORRECTNESS 0.0)~%~
                  - Correctness: ~,2F, [0 to 100]~%~
                  - Note: Your code's similarity ~,2F is below ~,2F for bonus.~%~
                  - Reference Solution:~%~s"
             (getf score-history :similarity-bonus-score)
             (getf score-history :violation-score)
             similarity
             +similarity-threshold+
             prof-sol))
    (:standard
     (format nil "Final Score: ~,2F, [0 to 100]~%Calculation: (MAX CORRECTNESS (+ (* CORRECTNESS CORRECTNESS-WEIGHT) (* SIMILARITY SIMILARITY-WEIGHT)))~%~
                    - Correctness: ~,2F, [0 to 100]~%~
                    - Correctness Weight: ~,2F, [0 to 1]~%~
                    - Similarity Weight: ~,2F, [0 to 1]~%~
                    - Similarity: ~,2F, [0 to 1]~%~
                    - Reference Solution:~%~s"
             (getf score-history :similarity-bonus-score)
             (getf score-history :violation-score)
             +correctness-weight+
             +style-weight+
             similarity
             prof-sol))))
